### ISSUE TITLE
Meet & Greet - Mozilla Downtown offices

### ISSUE THREAD

**Issue by dasaderi** [OpenCon-Cascadia/planning_in_the_open#18] opened 2019-01-08 22:21 UTC
I'm coordinating with Mozilla office on a plan and will update shortly.
In the meantime, I need help getting lightning talk speakers. In the program we planned for anywhere between 6-10 speakers.

Lightning talks so far:

- Stephanie Wright (Mozilla, Silver Sponsor)
- Dalia Corkrum (Whitman College) - bronze sponsor - wants to speak on Lever Press
- Ciera Martinez (UC Berkley, Mozilla fellow doing cool project with open data from natural history museums)
- Dan Zuckerman (OHSU) @rchampieux will reach out and ask
- Johnny Uriarte-Lopez‎ (OHSU, Demian Fair lab)

- Possibly Daniela (Me) give a 3 minute talk about PREreview.
- Possibly Danielle about collaboration and competition in open scholarship.

@xolotl will reach out to participants that have signed up and ask to submit inquiries. 
@rchampieux will reach out to sponsors to ask if they want to talk.

Also need help making bingo cards. @xolotl volunteered to help. @daniellecrobinson, wanna help too?  Thanks!

**Comment by dasaderi** [comment] 2019-01-08 22:26
Regarding the CoC for the Meet & Greet, we will have to operate under Mozilla Community Guidelines. I'm asking, but I think we will need to update the website to reflect that for the Friday.

**Comment by pamelapierce** [comment] 2019-01-08 22:35
@dasaderi I just want to make sure I'm clear. I saw the email that you assigned # 18 to me. Where is the list that tells me what number 18 is? I would rather ask than not do something.

**Comment by pamelapierce** [comment] 2019-01-08 22:38
Sorry. 18 is just the issue number.

**Comment by dasaderi** [comment] 2019-01-08 22:39
Oh, I'm sorry @PJP1313. I added you because you said you want to help with getting there early etc. So you can keep track of planning for that night. I hope that's okay. Feel free to remove yourself from this issue.

**Comment by daniellecrobinson** [comment] 2019-01-08 22:39
I'd love to help! If there's space, I would like to talk about collaboration and competition in open scholarship.

**Comment by pamelapierce** [comment] 2019-01-08 22:39
I will be there to help set up and do whatever is needed. I'm also excited to just go to the Mozilla Offices. I've never been to a big tech company's offices before. I definitely don't want to remove myself. I just wanted to make sure there wasn't anything else I needed to do.

**Comment by pamelapierce** [comment] 2019-01-08 22:40
It all makes more sense when I'm actually in the GitHub page. Via email all I see is "#18 assigned to Pam" The email doesn't say what the issue is.

**Comment by ashleyfarley** [comment] 2019-01-08 22:48
In regards to the Lightning talks - I am happy to help coordinate as well.
There have been a couple emails to us asking about the option. I am going
to request that they submit a short talk abstract to see if it fits with
our theme. It's a bit hard to tell without this.

**Comment by xolotl** [comment] 2019-01-08 23:42
@dasaderi sorry, now I'm confused...when you say "@xolotl will reach out to participants that have signed up and ask to submit inquiries." do you mean I should email people that have registered and indicated they will come to the Fri event at Mozilla and ask if they want to do a lightning talk? If so, I'm not sure I have access to the list of registrants.

**Comment by ashleyfarley** [comment] 2019-01-08 23:45
@xolotl I'm happy to send the email from our OpenCon Cascadia email account. If you could draft the email that would be very helpful. @rchampieux can you email me a list of participants? Or credentials for Eventbright? Thanks!

**Comment by xolotl** [comment] 2019-01-08 23:47
Sorry to be dense, but just to be clear, this is the mail we talked about on the last call that would give all registrants a general update on the event as well as ask if they wish to lightning talk?

**Comment by ashleyfarley** [comment] 2019-01-08 23:49
No apology needed - I copied this from the organizing notes document so I don't forget anything. 

"So excited that you registered! Did you see the schedule? Do you want to give a lighting talk Meet & Greet? Also, do you have a project for the do-a-thon? Include the official Twitter hashtag #OpenConCascadia19"

**Comment by xolotl** [comment] 2019-01-08 23:55
OK, I'll take a stab at an email draft after I close the parens on this day job thing I'm in the middle of.

**Comment by dasaderi** [comment] 2019-01-15 22:47
Here are some notes from the meeting with Katt Taylor, Mozilla office space manager.

- Room set up: ~30-40 total seats (including high chairs, couches, and wall bench) with space to mingle and walk around. We will have music (if we want) and AV access.

- Catering: Portland Pedal Power has several option. I made an account and we can choose from them. My favorite are Cafe Yum and Thai Peacock. PPP will deliver the food at 4:45pm and set everything up. At the end of the event they will come to clean up and pick up leftovers that will go to local shelters. We have the option to ask for service. That would be required if we want to have alcohol. The new Mozilla policy for event alcohol is that it's served by a trained bar tender. Unless we have someone internally that can and want to do that, we would need someone external. The alternative is that we don't serve alcohol. 

- Drinks: Katt will order drinks for us through her vendor. We need to tell her number of people and if we want alcoholic options. She will also order attractive non-alcoholic options.

TODO for me: 
- [x] contact Steph and Ann Marie to ask about Mozilla cost center account for beverage delivery.

**Comment by pamelapierce** [comment] 2019-01-15 23:06
I think we should simplify our lives and not serve alcohol at the event. There is enough places in the surrounding area that people can get drinks together after if they want.

**Comment by ashleyfarley** [comment] 2019-01-16 00:15
I agree. It will be easier and cheaper. I’m also biased as I’m taking a
break from alcohol :)

**Comment by dasaderi** [comment] 2019-01-16 00:35
Perfect! That makes things easier!

**Comment by ashleyfarley** [comment] 2019-01-16 17:12
I vote for Cafe Yum - I really love them - lots of options for all dietary needs.

**Comment by rchampieux** [comment] 2019-01-16 17:13
Haha....I have a Cafe Yum obsession.

**Comment by dasaderi** [comment] 2019-01-16 18:00
Yeah, I love Cafe Yum too! They are advising platters for a standing event, but we can do whatever we want. Cafe Yum can be an option for Saturday too. I'll keep you posted.

**Comment by LuciMoore** [comment] 2019-01-16 21:41
If it's alright with everyone I'd like to invite this Build EXITO student to give a lightning talk. I don't remember his name at the moment, but he works in Dr. Damien Fair's lab and is super brilliant. He recently completed a project where he helped create this quality control system for an open source MRI imaging database. It identified data that was too low-quality for researchers to use and also processed some data differently to make it higher quality, bringing the total percentage of quality useable data on the site from like 30 to 50%. Very impressive work

**Comment by rchampieux** [comment] 2019-01-16 21:42
Go for it!!!!

**Comment by LuciMoore** [comment] 2019-01-16 22:52
great, he agreed to give a lightning talk! his name is Johnny Uriarte-Lopez‎

**Comment by dasaderi** [comment] 2019-01-18 00:04
Here is the proposed Menu from Portland Pedal Power. They think that for the kind of event we are running, it's better to get something like this. It's from Whole Foods, which I don't love as I recently learned they use prison labor (like they have a factory inside a prison kinda labor!). But here it is. I can ask for a Cafe Yum estimate, even though I do think Cafe Yum is a great option for Saturday.

Total $789.10 for a headcount of 50 (to be updated).

- Mediterranean Mezze Platter (V) ($100.00) 18-20 people                   

- Vegetarian Tapas Platter (V) ($86.00) 18-20 people                                                                                                                                          

- Appetizer Platters: Small Baba Ghanouj (GF, Vg) ($36.00) 10-12 people 

- Hummus (Vg) ($30.00) 10-12  

- Salads Greek (V) (4 @ $46.00 = $184.00) serves 48                                                                                                                                           

- Lebanese Pastry Platter Large (V) (3 @ $66.00 = $198.00)

Order Details 
Mediterranean Mezze Platter (V): Hummus, baba ghanouj, olives, feta cheese, pickled vegetables, pita bread 
Vegetarian Tapas Platter (V) Fatayer spinach pies, falafel, kishek sfeeha pie, vegetarian filled grape leaves, tahini 
Baba Ghanouj (GF, Vg) Eggplant, tahini, lemon, garlic - Served with fresh vegetables 
Hummus (Vg) Garbanzo, tahini, lemon, garlic - Served with fresh vegetables

**Comment by xolotl** [comment] 2019-01-22 22:57
Are bingo cards still a need? I could help with that. Sorry, I'm having a hard time staying in the loop on what needs to be done.

**Comment by dasaderi** [comment] 2019-01-22 23:04
Sorry about that, @xolotl. We are having another meeting this Friday. Have you not received the invite to last week's one? Sorry if you haven't. I thought I had added you. 

@daniellecrobinson is doing the bingo cards. She posted on [Twitter](https://twitter.com/daniellecrobins/status/1086419926036885504) asking for additional things to add to the card. I don't think she needs additional help, but maybe?

**Comment by xolotl** [comment] 2019-01-22 23:08
@dasaderi sorry, I didn't get any calendar invites. My email is nate@xolotl.org. I'm open to helping more, I've just found it hard to figure out where.

**Comment by dasaderi** [comment] 2019-01-22 23:14
Sorry, it says you are in the list. I just deleted your name and re-added you. Did you receive a calendar invite every Friday until Feb 7?

**Comment by xolotl** [comment] 2019-01-22 23:19
@dasaderi ok, now I have an invite and have accepted. Are we lacking registrations, or near capacity?

**Comment by ashleyfarley** [comment] 2019-01-22 23:20
We have 50 open spots - so it would be great to amp up registrations

**Comment by rchampieux** [comment] 2019-01-23 00:13
We were aiming for 100 - 120, but I set-up Eventbrite for 150 just in case.  If we assume maybe 15% of folks won't show, I think getting 120 - 150 registered would be great.  Lilly and I build the food budget for aprox 100, but we set some reserve aside just in case.

**Comment by rchampieux** [comment] 2019-01-23 00:14
@xolotl have you had a chance to promote through your tech network and Calagator?  I think that would be helpful for outreach.

**Comment by xolotl** [comment] 2019-01-23 00:20
@rchampieux so that means we have about 100 registered already?

A while back I saw that it was already listed on Calagator, so someone had already taken care of that. I promoted to PSU folks and the tech community. I will do some more but wanted to see how close/far away we were from our attendance goals/limits.

**Comment by rchampieux** [comment] 2019-01-23 00:22
Yup, that's right we are at 99 @xolotl .  Thanks for promoting to those communities!  Do you know anyone in the open hardware / maker communities?  I was thinking that would be other good target.

**Comment by xolotl** [comment] 2019-01-23 00:38
I may be able to reach some makers. I'll work on that. My guess is that we'll get a few more registrations next week without doing more than continued promotion, so it seems like we will end up close to our goal.

**Comment by dasaderi** [comment] 2019-01-26 00:01
@daniellecrobinson will email bingo cards to @walecain for printing. 

@PJP1313 will bring little pencils from library.

Daniela will bring $50 Powell's gift card.

**Closed as completed** 2019-02-04 04:35 UTC
Labels: Priority
